-----------------------------------------------------------

-- Notes:


-----------------------------------------------------------

USE [SEInventory]
GO

-----------------------------------------------------------

CREATE TRIGGER [app].[Trigger_Users_DELETE]
ON [app].[Users] AFTER DELETE
AS

BEGIN 

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @NAME varchar(250)
	DECLARE @PASS_SALT varchar(250)
	DECLARE @PASS_HASH varchar(250)
	DECLARE @ROLE_ID int
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = [ID] FROM DELETED
	SELECT @NAME = [NAME] FROM DELETED
	SELECT @PASS_SALT = PASS_SALT FROM DELETED
	SELECT @PASS_HASH = PASS_HASH FROM DELETED
	SELECT @ROLE_ID = ROLE_ID FROM DELETED
	SELECT @CREATED_BY = CREATED_BY FROM DELETED
	SELECT @CREATED_DATE = CREATED_DATE FROM DELETED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM DELETED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM DELETED

	UPDATE [hist].[Audit_Users]
	SET INEFFECTIVE_DATE = GETDATE()
	WHERE INEFFECTIVE_DATE IS NULL
	AND [ID] = @ID;

	INSERT INTO [hist].[Audit_Users] (EFFECTIVE_DATE,INEFFECTIVE_DATE,[ID],[NAME],PASS_SALT,PASS_HASH,ROLE_ID,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (DATEADD(ms, 10,GETDATE()),GETDATE(),@ID,@NAME,@PASS_SALT,@PASS_HASH,@ROLE_ID,0,1,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE); 		  
END

GO

-----------------------------------------------------------

CREATE TRIGGER [app].[Trigger_Users_INSERT]
ON [app].[Users] AFTER INSERT
AS

BEGIN 

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @NAME varchar(250)
	DECLARE @PASS_SALT varchar(250)
	DECLARE @PASS_HASH varchar(250)
	DECLARE @ROLE_ID int
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = [ID] FROM INSERTED
	SELECT @NAME = [NAME] FROM INSERTED
	SELECT @PASS_SALT = PASS_SALT FROM INSERTED
	SELECT @PASS_HASH = PASS_HASH FROM INSERTED
	SELECT @ROLE_ID = ROLE_ID FROM INSERTED
	SELECT @CREATED_BY = CREATED_BY FROM INSERTED
	SELECT @CREATED_DATE = CREATED_DATE FROM INSERTED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM INSERTED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM INSERTED

	INSERT INTO [hist].[Audit_Users] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ID,[NAME],PASS_SALT,PASS_HASH,ROLE_ID,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (GETDATE(),NULL,@ID,@NAME,@PASS_SALT,@PASS_HASH,@ROLE_ID,1,0,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE); 		  
END

GO

-----------------------------------------------------------

CREATE TRIGGER [app].[Trigger_Users_UPDATE]
ON [app].[Users] AFTER UPDATE
AS

BEGIN 

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @NAME varchar(250)
	DECLARE @PASS_SALT varchar(250)
	DECLARE @PASS_HASH varchar(250)
	DECLARE @ROLE_ID int
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = [ID] FROM INSERTED
	SELECT @NAME = [NAME] FROM INSERTED
	SELECT @PASS_SALT = PASS_SALT FROM INSERTED
	SELECT @PASS_HASH = PASS_HASH FROM INSERTED
	SELECT @ROLE_ID = ROLE_ID FROM INSERTED
	SELECT @CREATED_BY = CREATED_BY FROM INSERTED
	SELECT @CREATED_DATE = CREATED_DATE FROM INSERTED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM INSERTED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM INSERTED

	UPDATE [hist].[Audit_Users]
	SET INEFFECTIVE_DATE = GETDATE()
	WHERE INEFFECTIVE_DATE IS NULL 
	AND [ID] = @ID;
		
	INSERT INTO [hist].[Audit_Users] (EFFECTIVE_DATE,INEFFECTIVE_DATE,[ID],[NAME],PASS_SALT,PASS_HASH,ROLE_ID,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (GETDATE(),NULL,@ID,@NAME,@PASS_SALT,@PASS_HASH,@ROLE_ID,0,0,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE);
END

GO

-----------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_Series_DELETE]
ON [app].[Series] AFTER DELETE
AS

BEGIN

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @SERIES_NAME varchar(250)
	DECLARE @DESCRIPTION varchar(250)
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = ID FROM DELETED
	SELECT @SERIES_NAME = SERIES_NAME FROM DELETED
	SELECT @DESCRIPTION = DESCRIPTION FROM DELETED
	SELECT @CREATED_BY = CREATED_BY FROM DELETED
	SELECT @CREATED_DATE = CREATED_DATE FROM DELETED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM DELETED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM DELETED

	UPDATE [hist].[Audit_Series]
	SET INEFFECTIVE_DATE = GETDATE()
	WHERE INEFFECTIVE_DATE IS NULL
	AND ID = @ID;

	INSERT INTO [hist].[Audit_Series] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ID,SERIES_NAME,DESCRIPTION,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (DATEADD(ms, 10,GETDATE()),GETDATE(),@ID,@SERIES_NAME,@DESCRIPTION,0,1,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE); 		  
END

GO

-----------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_Series_INSERT]
ON [app].[Series] AFTER INSERT
AS

BEGIN

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @SERIES_NAME varchar(250)
	DECLARE @DESCRIPTION varchar(250)
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = ID FROM INSERTED
	SELECT @SERIES_NAME = SERIES_NAME FROM INSERTED
	SELECT @DESCRIPTION = DESCRIPTION FROM INSERTED
	SELECT @CREATED_BY = CREATED_BY FROM INSERTED
	SELECT @CREATED_DATE = CREATED_DATE FROM INSERTED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM INSERTED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM INSERTED

	INSERT INTO [hist].[Audit_Series] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ID,SERIES_NAME,DESCRIPTION,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (GETDATE(),NULL,@ID,@SERIES_NAME,@DESCRIPTION,1,0,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE); 		  
END

GO

-----------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_Series_UPDATE]
ON [app].[Series] AFTER UPDATE
AS

BEGIN

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @SERIES_NAME varchar(250)
	DECLARE @DESCRIPTION varchar(250)
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = ID FROM INSERTED
	SELECT @SERIES_NAME = SERIES_NAME FROM INSERTED
	SELECT @DESCRIPTION = DESCRIPTION FROM INSERTED
	SELECT @CREATED_BY = CREATED_BY FROM INSERTED
	SELECT @CREATED_DATE = CREATED_DATE FROM INSERTED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM INSERTED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM INSERTED

	UPDATE [hist].[Audit_Series]
	SET INEFFECTIVE_DATE = GETDATE()
	WHERE INEFFECTIVE_DATE IS NULL 
	AND ID = @ID;
		
	INSERT INTO [hist].[Audit_Series] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ID,SERIES_NAME,DESCRIPTION,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (GETDATE(),NULL,@ID,@SERIES_NAME,@DESCRIPTION,0,0,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE);
END

GO

-----------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_Brands_DELETE]
ON [app].[Brands] AFTER DELETE
AS

BEGIN 

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @BRAND_NAME varchar(50)
	DECLARE @DESCRIPTION varchar(250)
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = ID FROM DELETED
	SELECT @BRAND_NAME = BRAND_NAME FROM DELETED
	SELECT @DESCRIPTION = DESCRIPTION FROM DELETED
	SELECT @CREATED_BY = CREATED_BY FROM DELETED
	SELECT @CREATED_DATE = CREATED_DATE FROM DELETED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM DELETED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM DELETED

	UPDATE [hist].[Audit_Brands]
	SET INEFFECTIVE_DATE = GETDATE()
	WHERE INEFFECTIVE_DATE IS NULL
	AND ID = @ID;

	INSERT INTO [hist].[Audit_Brands] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ID,BRAND_NAME,DESCRIPTION,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (DATEADD(ms, 10,GETDATE()),GETDATE(),@ID,@BRAND_NAME,@DESCRIPTION,0,1,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE); 		  
END

GO

-----------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_Brands_INSERT]
ON [app].[Brands] AFTER INSERT
AS

BEGIN 

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @BRAND_NAME varchar(50)
	DECLARE @DESCRIPTION varchar(250)
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = ID FROM INSERTED
	SELECT @BRAND_NAME = BRAND_NAME FROM INSERTED
	SELECT @DESCRIPTION = DESCRIPTION FROM INSERTED
	SELECT @CREATED_BY = CREATED_BY FROM INSERTED
	SELECT @CREATED_DATE = CREATED_DATE FROM INSERTED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM INSERTED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM INSERTED

	INSERT INTO [hist].[Audit_Brands] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ID,BRAND_NAME,DESCRIPTION,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (GETDATE(),NULL,@ID,@BRAND_NAME,@DESCRIPTION,1,0,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE); 		  
END

GO

-----------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_Brands_UPDATE]
ON [app].[Brands] AFTER UPDATE
AS

BEGIN 

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @BRAND_NAME varchar(50)
	DECLARE @DESCRIPTION varchar(250)
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = ID FROM INSERTED
	SELECT @BRAND_NAME = BRAND_NAME FROM INSERTED
	SELECT @DESCRIPTION = DESCRIPTION FROM INSERTED
	SELECT @CREATED_BY = CREATED_BY FROM INSERTED
	SELECT @CREATED_DATE = CREATED_DATE FROM INSERTED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM INSERTED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM INSERTED

	UPDATE [hist].[Audit_Brands]
	SET INEFFECTIVE_DATE = GETDATE()
	WHERE INEFFECTIVE_DATE IS NULL 
	AND ID = @ID;
		
	INSERT INTO [hist].[Audit_Brands] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ID,BRAND_NAME,DESCRIPTION,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (GETDATE(),NULL,@ID,@BRAND_NAME,@DESCRIPTION,0,0,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE);
END

GO

-----------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_Collections_DELETE]
ON [app].[Collections] AFTER DELETE
AS

BEGIN

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @COLLECTION_NAME varchar(250)
	DECLARE @DESCRIPTION varchar(250)
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = ID FROM DELETED
	SELECT @COLLECTION_NAME = COLLECTION_NAME FROM DELETED
	SELECT @DESCRIPTION = DESCRIPTION FROM DELETED
	SELECT @CREATED_BY = CREATED_BY FROM DELETED
	SELECT @CREATED_DATE = CREATED_DATE FROM DELETED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM DELETED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM DELETED

	UPDATE [hist].[Audit_Collections]
	SET INEFFECTIVE_DATE = GETDATE()
	WHERE INEFFECTIVE_DATE IS NULL
	AND ID = @ID;

	INSERT INTO [hist].[Audit_Collections] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ID,COLLECTION_NAME,DESCRIPTION,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (DATEADD(ms, 10,GETDATE()),GETDATE(),@ID,@COLLECTION_NAME,@DESCRIPTION,0,1,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE); 		  
END

GO

-----------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_Collections_INSERT]
ON [app].[Collections] AFTER INSERT
AS

BEGIN

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @COLLECTION_NAME varchar(250)
	DECLARE @DESCRIPTION varchar(250)
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = ID FROM INSERTED
	SELECT @COLLECTION_NAME = COLLECTION_NAME FROM INSERTED
	SELECT @DESCRIPTION = DESCRIPTION FROM INSERTED
	SELECT @CREATED_BY = CREATED_BY FROM INSERTED
	SELECT @CREATED_DATE = CREATED_DATE FROM INSERTED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM INSERTED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM INSERTED

	INSERT INTO [hist].[Audit_Collections] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ID,COLLECTION_NAME,DESCRIPTION,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (GETDATE(),NULL,@ID,@COLLECTION_NAME,@DESCRIPTION,1,0,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE); 		  
END

GO

-----------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_Collections_UPDATE]
ON [app].[Collections] AFTER UPDATE
AS

BEGIN

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @COLLECTION_NAME varchar(250)
	DECLARE @DESCRIPTION varchar(250)
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = ID FROM INSERTED
	SELECT @COLLECTION_NAME = COLLECTION_NAME FROM INSERTED
	SELECT @DESCRIPTION = DESCRIPTION FROM INSERTED
	SELECT @CREATED_BY = CREATED_BY FROM INSERTED
	SELECT @CREATED_DATE = CREATED_DATE FROM INSERTED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM INSERTED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM INSERTED

	UPDATE [hist].[Audit_Collections]
	SET INEFFECTIVE_DATE = GETDATE()
	WHERE INEFFECTIVE_DATE IS NULL 
	AND ID = @ID;
		
	INSERT INTO [hist].[Audit_Collections] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ID,COLLECTION_NAME,DESCRIPTION,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (GETDATE(),NULL,@ID,@COLLECTION_NAME,@DESCRIPTION,0,0,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE);
END

GO

-----------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_ItemComments_DELETE]
ON [app].[ItemComments] AFTER DELETE
AS

BEGIN 

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @ITEM_ID int
	DECLARE @COMMENT varchar(max)
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = ID FROM DELETED
	SELECT @ITEM_ID = ITEM_ID FROM DELETED
	SELECT @COMMENT = COMMENT FROM DELETED
	SELECT @CREATED_BY = CREATED_BY FROM DELETED
	SELECT @CREATED_DATE = CREATED_DATE FROM DELETED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM DELETED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM DELETED

	UPDATE [hist].[Audit_ItemComments]
	SET INEFFECTIVE_DATE = GETDATE()
	WHERE INEFFECTIVE_DATE IS NULL
	AND ITEM_ID = @ITEM_ID
	AND ID = @ID;

	INSERT INTO [hist].[Audit_ItemComments] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ITEM_ID,ID,COMMENT,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (DATEADD(ms, 10,GETDATE()),GETDATE(),@ITEM_ID,@ID,@COMMENT,0,1,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE); 		  
END

GO

-----------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_ItemComments_INSERT]
ON [app].[ItemComments] AFTER INSERT
AS

BEGIN 

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @ITEM_ID int
	DECLARE @COMMENT varchar(max)
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = ID FROM INSERTED
	SELECT @ITEM_ID = ITEM_ID FROM INSERTED
	SELECT @COMMENT = COMMENT FROM INSERTED
	SELECT @CREATED_BY = CREATED_BY FROM INSERTED
	SELECT @CREATED_DATE = CREATED_DATE FROM INSERTED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM INSERTED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM INSERTED

	INSERT INTO [hist].[Audit_ItemComments] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ITEM_ID,ID,COMMENT,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (GETDATE(),NULL,@ITEM_ID,@ID,@COMMENT,1,0,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE); 		  
END

GO

-----------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_ItemComments_UPDATE]
ON [app].[ItemComments] AFTER UPDATE
AS

BEGIN 

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @ITEM_ID int
	DECLARE @COMMENT varchar(max)
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = ID FROM INSERTED
	SELECT @ITEM_ID = ITEM_ID FROM INSERTED
	SELECT @CREATED_BY = CREATED_BY FROM INSERTED
	SELECT @CREATED_DATE = CREATED_DATE FROM INSERTED
	SELECT @COMMENT = COMMENT FROM INSERTED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM INSERTED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM INSERTED

	UPDATE [hist].[Audit_ItemComments]
	SET INEFFECTIVE_DATE = GETDATE()
	WHERE INEFFECTIVE_DATE IS NULL 
	AND ITEM_ID = @ITEM_ID
	AND ID = @ID;
		
	INSERT INTO [hist].[Audit_ItemComments] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ITEM_ID,ID,COMMENT,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (GETDATE(),NULL,@ITEM_ID,@ID,@COMMENT,0,0,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE);
END

GO

-----------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_Items_DELETE]
ON [app].[Items] AFTER DELETE
AS

BEGIN

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @COLLECTION_ID int
	DECLARE @STATUS varchar(10)
	DECLARE @TYPE varchar(15)
	DECLARE @BRAND_ID int
	DECLARE @SERIES_ID int
	DECLARE @NAME varchar(100) 
	DECLARE @DESCRIPTION varchar(250)
	DECLARE @FORMAT varchar(15)  
	DECLARE @SIZE varchar(10)
	DECLARE @YEAR int
	DECLARE @PHOTO varchar(max) 
	DECLARE @CREATED_BY varchar(100) 
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime
	
	SELECT @ID = ID FROM DELETED
	SELECT @COLLECTION_ID = COLLECTION_ID FROM DELETED
	SELECT @STATUS = STATUS	FROM DELETED
	SELECT @TYPE = TYPE	FROM DELETED
	SELECT @BRAND_ID = BRAND_ID FROM DELETED
	SELECT @SERIES_ID = SERIES_ID FROM DELETED
	SELECT @NAME = NAME FROM DELETED
	SELECT @DESCRIPTION = DESCRIPTION FROM DELETED
	SELECT @FORMAT = FORMAT FROM DELETED
	SELECT @SIZE = SIZE	FROM DELETED
	SELECT @YEAR = YEAR	FROM DELETED
	SELECT @PHOTO = PHOTO FROM DELETED
	SELECT @CREATED_BY = CREATED_BY	FROM DELETED
	SELECT @CREATED_DATE = CREATED_DATE	FROM DELETED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM DELETED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM DELETED

	UPDATE [hist].[Audit_Items]
	SET INEFFECTIVE_DATE = GETDATE()
	WHERE INEFFECTIVE_DATE IS NULL
	AND ID = @ID;

	INSERT INTO [hist].[Audit_Items] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ID,COLLECTION_ID,STATUS,TYPE,BRAND_ID,SERIES_ID,NAME,DESCRIPTION,FORMAT,SIZE,YEAR,PHOTO,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (DATEADD(ms, 10,GETDATE()),GETDATE(),@ID,@COLLECTION_ID,@STATUS,@TYPE,@BRAND_ID,@SERIES_ID,@NAME,@DESCRIPTION,@FORMAT,@SIZE,@YEAR,@PHOTO,0,1,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE); 		  
END

GO

-----------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_Items_INSERT]
ON [app].[Items] AFTER INSERT
AS

BEGIN

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @COLLECTION_ID int
	DECLARE @STATUS varchar(10)
	DECLARE @TYPE varchar(15)
	DECLARE @BRAND_ID int
	DECLARE @SERIES_ID int
	DECLARE @NAME varchar(100) 
	DECLARE @DESCRIPTION varchar(250)
	DECLARE @FORMAT varchar(15)  
	DECLARE @SIZE varchar(10)
	DECLARE @YEAR int
	DECLARE @PHOTO varchar(max) 
	DECLARE @CREATED_BY varchar(100) 
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = ID FROM INSERTED
	SELECT @COLLECTION_ID = COLLECTION_ID FROM INSERTED
	SELECT @STATUS = STATUS	FROM INSERTED
	SELECT @TYPE = TYPE	FROM INSERTED
	SELECT @BRAND_ID = BRAND_ID FROM INSERTED
	SELECT @SERIES_ID = SERIES_ID FROM INSERTED
	SELECT @NAME = NAME FROM INSERTED
	SELECT @DESCRIPTION = DESCRIPTION FROM INSERTED
	SELECT @FORMAT = FORMAT FROM INSERTED
	SELECT @SIZE = SIZE	FROM INSERTED
	SELECT @YEAR = YEAR	FROM INSERTED
	SELECT @PHOTO = PHOTO FROM INSERTED
	SELECT @CREATED_BY = CREATED_BY	FROM INSERTED
	SELECT @CREATED_DATE = CREATED_DATE	FROM INSERTED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM INSERTED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM INSERTED

	INSERT INTO [hist].[Audit_Items] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ID,COLLECTION_ID,STATUS,TYPE,BRAND_ID,SERIES_ID,NAME,DESCRIPTION,FORMAT,SIZE,YEAR,PHOTO,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (GETDATE(),NULL,@ID,@COLLECTION_ID,@STATUS,@TYPE,@BRAND_ID,@SERIES_ID,@NAME,@DESCRIPTION,@FORMAT,@SIZE,@YEAR,@PHOTO,1,0,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE); 		  
END

GO

-------------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_Items_UPDATE]
ON [app].[Items] AFTER UPDATE
AS

BEGIN

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @COLLECTION_ID int
	DECLARE @STATUS varchar(10)
	DECLARE @TYPE varchar(15)
	DECLARE @BRAND_ID int
	DECLARE @SERIES_ID int
	DECLARE @NAME varchar(100) 
	DECLARE @DESCRIPTION varchar(250)
	DECLARE @FORMAT varchar(15)  
	DECLARE @SIZE varchar(10)
	DECLARE @YEAR int
	DECLARE @PHOTO varchar(max)  
	DECLARE @CREATED_BY varchar(100) 
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = ID FROM INSERTED
	SELECT @COLLECTION_ID = COLLECTION_ID FROM INSERTED
	SELECT @STATUS = STATUS	FROM INSERTED
	SELECT @TYPE = TYPE	FROM INSERTED
	SELECT @BRAND_ID = BRAND_ID FROM INSERTED
	SELECT @SERIES_ID = SERIES_ID FROM INSERTED
	SELECT @NAME = NAME FROM INSERTED
	SELECT @DESCRIPTION = DESCRIPTION FROM INSERTED
	SELECT @FORMAT = FORMAT FROM INSERTED
	SELECT @SIZE = SIZE	FROM INSERTED
	SELECT @YEAR = YEAR	FROM INSERTED
	SELECT @PHOTO = PHOTO FROM INSERTED
	SELECT @CREATED_BY = CREATED_BY	FROM INSERTED
	SELECT @CREATED_DATE = CREATED_DATE	FROM INSERTED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM INSERTED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM INSERTED

	UPDATE [hist].[Audit_Items]
	SET INEFFECTIVE_DATE = GETDATE()
	WHERE INEFFECTIVE_DATE IS NULL 
	AND ID = @ID;
		
	INSERT INTO [hist].[Audit_Items] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ID,COLLECTION_ID,STATUS,TYPE,BRAND_ID,SERIES_ID,NAME,DESCRIPTION,FORMAT,SIZE,YEAR,PHOTO,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (GETDATE(),NULL,@ID,@COLLECTION_ID,@STATUS,@TYPE,@BRAND_ID,@SERIES_ID,@NAME,@DESCRIPTION,@FORMAT,@SIZE,@YEAR,@PHOTO,0,0,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE);
END

GO

-----------------------------------------------------------


